### ISSUE TITLE
AttributeError: type object 'Integral' has no attribute 'sugeno_fuzzy_integral_generalized'

### ISSUE THREAD

**Issue by soongxian** [Rohit-Kundu/Fuzzy-Integral-Covid-Detection#1]
Hi sir, would like to enquire about line 46 in ensemble.py, at X_agg = integrals.sugeno_fuzzy_integral_generalized(X,measure). It is found that there is no attribute for integrals, can I know what type of import is used for integrals attribute?

**Comment by Rohit-Kundu** [comment]
Sorry for the typographical error (should have been ``sugeno_integral.sugeno_fuzzy_integral_generalized(X, measure)``. Have fixed the issue.
