### ISSUE TITLE
ValueError: Found input variables with inconsistent numbers of samples: [204, 745]

### ISSUE THREAD

**Issue by soongxian** [Rohit-Kundu/Fuzzy-Integral-Covid-Detection#2]
Hi, can I know how to solve this issue, this happens at main.py line 108 <ensemble_sugeno(labels,prob1,prob2,prob3,prob4)>

**Comment by Rohit-Kundu** [comment]
In `ensemble.py` Line 7, the labels parameter has been hard-coded. I suggest you change the code snippet such that it works on your dataset.

```
    labels=[]
    for i in range(376):
        labels.append(0)
    for i in range(369):
        labels.append(1)
    labels = np.asarray(labels)
```

In the future, we'll try to avoid such hard-coded snippets. For now, please change this according to your experiment.
